### PR TITLE
enh: format CLI argparse

### PR DESCRIPTION
**Pull request by paulolimac**
- style `args.py` with PEP8.
- add short synonyms for all CLI options.

### CODE REVIEW

**Comment by paulolimac** [comment]
I rebased this my pull-requested branch, to sync it with all the new commits from this upstream repo.
Let me know if a mess something up.

**Comment by 1271** [comment]
Thanks for your work
I think it was worth then removing all unused code
It stayed there because nobody looked in the cli section

**Comment by paulolimac** [comment]
Thanks for your reply @1271 .
But I don't got what you said: I didn't removed nothing.

I did 2 things in my commits:
1. I added a *short option* (e.g.: `-a`, `-z`, `-d`, ...) for all `argparse.add` options.
2. I formatted all `argparse.add` lines, broken them in short lines, to be more readable.

I did not removed any code (nor unused code, nor commented code).

**Comment by 1271** [comment]
@paulolimac 
Oh. Sorry. My english is very bad
I would be glad if you removed the "dead code"

**Comment by paulolimac** [comment]
@1271 , dont worry, I dont speak English very well.
So do you want me to delete all comments from `../cli/args.py`?
If yes, I can do that.

**Comment by 1271** [comment]
> So do you want me to delete all comments from ../cli/args.py?

Yes. Thanks

**Pull request merged**
