### PR TITLE
Adding all english Madara themed websites

### PR DESCRIPTION
**Pull request by Middlepepper**
Added all the english Madara themed website I could find

|Website   |Theme   |Tested with --force-provider   |
| ------------ | ------------ | ------------ |
|https://allporncomic.com|Madara |Fails - need to update /manga/ to /porncomic/
|https://aloalivn.com|Madara |Works
|https://animangaes.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://aoc.moe|Madara | Website Down
|https://arangscans.com|Madara |Fails - ERROR:/manga_py/download_methods.py:65:YYYY-MM-DD HH:MM:SS,185:Error processing file: vol_001
|https://www.astrallibrary.net|Madara |Works
|https://bestmanhua.com|Madara |Works
|https://boyslove.me|Madara |Fails - 'NoneType' object has no attribute 'group'
|https://catonhead.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://www.cmreader.info|Madara |Fails 
|https://comickiba.com|Madara |Works
|https://reader.decadencescans.com|Madara |Fails - 'NoneType' object has no attribute 'group'
|https://disasterscans.com|Madara |Fails- [UnidentifiedImageError("cannot identify image file
|https://en.ruyamanga.com|Madara |Works
|https://einherjarscans.space|Madara |Website Down
|https://1stkissmanga.com|Madara |Fails - :No connection adapters were found for "data://1stkissmanga.com/
|https://1stkissmanhua.com|Madara | Fails - Image Processing error?
|https://freewebtooncoins.com|Madara |Website Down
|https://grazescans.com|Madara |Works
|https://heromanhua.com|Madara |Website Down
|https://herozscans.com|Madara |Works
|https://hiperdex.com|Madara |Works
|https://hscans.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://immortalupdates.com|Madara |Works
|https://isekaiscan.com|Madara |Website Down
|https://isekaiscanmanga.com|Madara |Works
|https://itsyourightmanhua.com|Madara |Works
|https://jjutsuscans.com|Madara |Works
|https://kisekimanga.com|Madara |Works
|https://kissmanga.in|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://lilymanga.com|Madara | /Manga/ is /ys/
|https://manga18.fun|Madara |Website Down
|https://manga18fx.com|Madara |Website Down
|https://manga347.com|Madara |Fails -AttributeError: 'NoneType' object has no attribute 'group'
|https://manga3s.com|Madara |Works
|https://manga68.com|Madara |Works
|https://mangabin.com|Madara |Works
|https://mangabob.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://mangachill.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://mangaclash.com|Madara |Works
|https://mangacultivator.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://www.mangadods.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://mangaeffect.com|Madara |Works
|https://mangagreat.com|Madara |Fail - Error ERROR:/manga_py/download_methods.py:65
|https://mangahentai.me|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group' (Need to change /manga/ to manga-hentai)
|https://mangakik.com|Madara |Works
|https://mangakiss.org|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group' (Need to change /manga/ to mangakiss)
|https://mangakomi.com|Madara |Works
|https://mangalord.com|Madara |Works
|https://manganelo.link|Madara |Website Down
|https://manganine.com|Madara |
|http://www.mangarave.com|Madara |
|https://manhwa.live|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://mangaread.co|Madara |
|https://www.mangaread.org|Madara |Works
|https://mangarockteam.com|Madara |Works
|https://mangarocky.com|Madara |Works
|https://mangaroma.com|Madara |Website Down
|https://mangasco.com|Madara |
|https://mangasushi.net|Madara |Works
|https://www.mangasy.com|Madara |
|https://mangatoo.com|Madara |
|https://mangaturf.com|Madara |Works
|https://mangatx.com|Madara |Works
|https://mangaus.xyz|Madara |
|https://mangaweebs.in|Madara |Website Down
|https://mangazuki.me|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|http://mangazukinew.online|Madara |Fails - IndexError: list index out of range
|https://manhuabox.net|Madara |Works
|https://manhuaes.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://manhuafast.com|Madara |
|https://manhuaga.com|Madara |Works
|https://manhuaplus.com|Madara |Fails - "ERROR:/manga_py/download_methods.py:65:,371:Error processing file: vol_500-0"
|https://manhuas.net|Madara |
|https://manhuasworld.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://www.manhuasy.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://manhuaus.com|Madara |
|https://manhwatop.com|Madara |
|https://manhwahentai.me|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://manhwa.club|Madara |
|https://manytoon.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://manytoon.me|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://milftoon.xxx|Madara |
|https://miraclescans.com|Madara | Website Down
|https://mixedmanga.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://mm-scans.com|Madara |Works
|https://mysticalmerries.com|Madara |
|https://nazarickscans.com|Madara |Website Down
|https://neatmanga.com|Madara |
|https://nekoscan.com|Madara |Works
|https://www.nightcomic.com|Madara |Works
|https://nitroscans.com|Madara |
|https://ntsvoidscans.com|Madara |Website Down
|https://onmanga.com|Madara |
|https://painfulnightzscan.com|Madara |Works
|https://www.pmscans.com|Madara |
|https://www.porncomixonline.net|Madara |
|https://primemanga.com|Madara |Website Down
|https://raiderscans.com|Madara |Website Down
|https://randomtranslations.com|Madara |Works
|https://readmanhua.net|Madara |
|https://new.renascans.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://s2manga.com|Madara |
|https://shieldmanga.club|Madara |Fails -IndexError: list index out of range
|http://shoujohearts.com|Madara |Fails -IndexError: list index out of range
|http://www.sixiangscans.com|Madara |
|https://skymanga.co|Madara |
|https://sleepytranslations.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://socialweebs.in|Madara |
|https://soloscanlation.site|Madara |Website Down
|https://thetopcomic.com|Madara |Fails - [UnidentifiedImageError("cannot identify image file
|https://365manga.com|Madara |Works
|https://www.toongod.com|Madara |
|https://toonily.com|Madara |
|https://toonily.net|Madara |Works
|https://toonpoint.com|Madara |Website Down
|https://topmanhua.com|Madara |
|https://tritinia.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://twilightscans.com|Madara |Fails - IndexError: list index out of range
|https://vanguardbun.com|Madara |Fails - Chapters list empty (even with chapters)
|https://voidscans.com|Madara |Website Down
|https://webnovel.live|Madara |Works
|https://webtoonily.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://webtoon.uk|Madara |Fails - need to update /manga/ to /webtoon/
|https://www.webtoon.xyz|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://wescans.xyz|Madara |Website Down
|https://woopread.com|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://wuxiaworld.site|Madara |Fails - need to update /manga/ to /novel/
|https://zinmanga.com|Madara |Works
|https://skscans.com|Madara |Works
|https://leviatanscans.com|Madara |Works
|https://manga1st.com|Madara |Fails - ERROR:/manga_py/download_methods.py:65
|https://manga1st.online|Madara |Fails - AttributeError: 'NoneType' object has no attribute 'group'
|https://imperfectcomic.com|Madara |Fails - need to update /manga/ to /comic/
|https://manga.ookamii.xyz|Madara |Fail - Error ERROR:/manga_py/download_methods.py:65
|https://mortalsgroove.com|Madara |Works

### CODE REVIEW

**Comment by 1271** [comment]
Wow. Let me know when it's finished.

And a little from myself:
This makes users think a little, but you can achieve the same effect using the `--force-provider` option.
https://github.com/manga-py/manga-py/blob/6cd53ea172400937ced576dc23af4e33e10c0bf3/manga_py/cli/_args_downloading.py#L111-L117

Example:
```bash
manga-py https://toonily.net/manga/star-martial-god-technique/ --force-provider http://isekaiscan.com/manga/_
```

Thanks in advance for your work.
I will wait for completion

**Comment by Middlepepper** [comment]
Wow that's good to know so I can use `--force-provider` to test if it works.

I've added them all to /provider/__init__.py do I need to make corresponding Sitename_com.py file for each or can it use theisekaiscan_com.py?

Just learning python so need alittle direction on what file I need to edit. is there a CONTRIBUTING.md?

**Comment by 1271** [comment]
> Just learning python so need alittle direction on what file I need to edit. is there a CONTRIBUTING.md?

Technically, all contributors are automatically counted by github.
But if this is important to you, you can create the CONTRIBUTING.md file. 
Screenshot_20210403_153520

> do I need to make corresponding Sitename_com.py file for each

No. It would be terrible if adding a new url required creating an empty file (or something similar) :cry: 

---

Urls inside the list (which you added, for example) are used to find the provider.

You can see here: 
https://github.com/manga-py/manga-py/blob/6cd53ea172400937ced576dc23af4e33e10c0bf3/manga_py/providers/__init__.py#L619-L630

**Comment by Middlepepper** [comment]
Thanks and sorry I meant more like [CONTRIBUTING.md](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md) as in a file to help people contributing with the structure and location of file etc.

**Comment by 1271** [comment]
Oh, this is my fault. Yes, it might be worth doing something like that.
I will definitely do it. Thanks!

Changes from this PR will be available in the next release.

**Pull request merged**
