### PR TITLE
cli: Add `--save-manga-info`

### PR DESCRIPTION
**Pull request by eduhoribe**
This option would save the details of the manga in a `info.json` file for future usage

### CODE REVIEW

**Comment by eduhoribe** [comment]
All changes have been made. Ready to merge.

**Comment by 1271** [comment]
Not sure if I'm ready to accept this, but I figured out exactly what you need.
A little later I will do it for you, but without breaking providers.
Thanks for your work. Don't cancel PR

**Comment by eduhoribe** [comment]
I understand. I was a little concerned about changing something wrong in the Provider class and breaking something.
The project has many things that I still don't know how it works. I'm sorry.
If I can help with anything else, please let me know.

**Comment by 1271** [comment]
It's okay, don't worry. The only problem is that this is not implemented for all providers. Providers have a book_meta method that was once added to get data from providers (but not all providers return correct data now)
Anyway, thanks for the work done. I really appreciate this.

**Comment by 1271** [comment]
Hi again. Perhaps you ever want to add this functionality to other providers?

Still, I decided to accept it. Expect a new minor version soon.

**Comment by eduhoribe** [comment]
Hello. I really would like to update other providers with this functionality.
Is there a list of priorities or something? Personal preference?
Thank you for accepting the changes \o/

**Comment by 1271** [comment]
No preferences. At your discretion.
Thanks for your work!

**Pull request merged**
